FF-491 relative timestamps
FileFighter/WebApp pull request #220
Opened 2021-07-25 15:46 UTC by qvalentin

2021-07-25 15:51 UTC, open-schnick requested changes
Check comment

2021-07-25 15:51 UTC, open-schnick commented on src/background/methods/dataTypes/time.ts
> +    if (relativeTime) {
Does empty string evaluate to _false_?

2021-07-25 16:16 UTC, qvalentin commented on src/background/methods/dataTypes/time.ts
> +    if (relativeTime) {
Yes.

2021-07-26 20:02 UTC, open-schnick commented on src/background/methods/dataTypes/time.ts
> +    if (relativeTime) {
then merge it

2021-07-26 20:02 UTC, open-schnick approved these changes

2021-07-26 20:02 UTC, merged