Selecting Files
FileFighter/WebApp pull request #39
Opened 2021-01-17 12:04 UTC by qvalentin

you will be able to select file from different folders at the same time. This way you can easily select what you want to delete/download.

Cypress tests are broken because cors is not working on the server.

2021-01-18 12:24 UTC, qvalentin commented on webapp_frontend/src/components/pages/filesytem/FileList.tsx
> +            folders?.forEach((e: FsEntity) => props.addToSelected(e));
this could cause doubled entries

2021-01-22 09:28 UTC, open-schnick commented
gonna review this tomorrow

2021-01-23 16:10 UTC, open-schnick commented
Looks good to me. Is the feature the fact that you can select the files with a checkbox?.  
One more thing tho. Can we implement a fixed placeholder for the "x files selected"? I am kinda annoid by the fact that the whole page shifts downwards, when first clicking. Also a good implementation could be a toast at the bottom of the page (like on dropbox)

2021-01-23 16:13 UTC, open-schnick commented on webapp_frontend/src/components/pages/filesytem/FileList.tsx
> +  // console.log("--------------------------------------------------------------------------------------")
production ready?

2021-01-23 16:13 UTC, open-schnick requested changes
code does look fine to me.

2021-01-23 16:17 UTC, qvalentin commented on webapp_frontend/src/components/pages/filesytem/FileList.tsx
> +  // console.log("--------------------------------------------------------------------------------------")
@gimleux fault :)

2021-01-25 19:49 UTC, open-schnick approved these changes

2021-01-25 19:50 UTC, open-schnick commented
merge it if you want

2021-01-26 16:13 UTC, merged